name: CI

on:
  push:
    branches: [ main, bvo024/ci_setup, bvo024/passing_tests, bvo024/failing_tests ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Add googletest files
      run: git submodule update --init

    - name: Build executable
      run: |
        cmake .
        make

    - name: Run tests
      run: bin/runRectangleTests
